steps:
  - name: gcr.io/cloud-builders/docker
    id: build-image
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/app-backend:$SHORT_SHA
      - -f
      - src/Dockerfile
      - src
  
  - name: gcr.io/cloud-builders/docker
    id: push-app-backend
    waitFor:
      - build-image
    args:
      - push
      - gcr.io/$PROJECT_ID/app-backend:$SHORT_SHA

  - name: gcr.io/cloud-builders/gke-deploy
    id: deploy-app-backend
    waitFor:
      - push-app-backend
    args:
      - run
      - --filename=infrastructure/app/
      - -R
      - --image=gcr.io/$PROJECT_ID/app-backend:$SHORT_SHA
      - -o output/app-backend
      - --namespace=${_NAMESPACE}
      - --location=${_REGION}
      - --cluster=${_CLUSTER}

timeout: 1200s
